# NB 42 - Reach-targeting features + observability smoke (gpt-5-mini)

**Purpose.** End-to-end verification of the two new reach-targeting features and the new output
artefacts they feed, on small OpenAI `gpt-5-mini` runs.

- **Feature 1 - persuadable targeting.** With `reach_a<1.0` and `reach_targeting_a="persuadable"`,
  each side keeps the most *undecided* audience members (smallest `|ground-truth package index|`).
- **Feature 2 - centrality targeting.** `reach_targeting_a="degree"` (on a Barabasi-Albert graph)
  keeps the most *central* audience members.
- **New outputs (byproduct).** `agent_prompts.csv` (full system+user+response for a stratified
  sample of agents), `reached_by_a/_b` flags in `agent_attributes.csv`, `bucket_summary.csv`,
  `targeting_diagnostics.csv`, plus the new O2 figures.

**Model / canon.** `gpt-5-mini` (OpenAI) for both messaging and surveys, `thinking=False`,
`day0_anchor=ground_truth_with_rationale`, and the production memory canon
`memory={"day0_anchor":{"ttl_days":1}}` (Day-0 anchor trails off after Day 1) - matching the
`tier1` AIRE runs. The API key is read automatically from `data/api_key.csv` (repo root) by the
simulation; the setup cell also loads it for a display sanity check.

**Caveat.** At `n=24` the committed-minority buckets (A-only / B-only) are ~1 agent each, so
per-bucket numbers there are noisy. This NB checks *plumbing*, not effect sizes.

**Cost.** ~24 agents x 3 days x 6 policies + anchoring + surveys + reflections + peer messaging is
a few hundred `gpt-5-mini` calls per run (x2 runs) - a few minutes and pennies of API cost.

## 1. Setup + local-server ping

In [1]:
import os, sys, json, logging
from pathlib import Path

sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '../src')))

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s', force=True)
for noisy in ('httpx', 'openai', 'httpcore'):
    logging.getLogger(noisy).setLevel(logging.WARNING)

import numpy as np
import pandas as pd

from cag.io.survey import load
from cag.io.llm import load_api_key
from cag.__main__ import build_nation
from cag.abm.sim import run_simulation, SIM_CONFIG
from cag.io.results import _write_all_csvs, _serialise_config, _atomic_write_json
from cag.io.plots import save_result_plots

PROVIDER = 'openai'
MODEL    = 'gpt-5-mini'

# The sim resolves the key itself from <repo>/data/api_key.csv; load here just for a sanity check.
API_KEY = load_api_key(PROVIDER, csv_path='../data/api_key.csv')
print(f'Provider/model : {PROVIDER}/{MODEL}')
print(f'API key loaded : {bool(API_KEY)} (len={len(API_KEY) if API_KEY else 0})')

Provider/model : openai/gpt-5-mini
API key loaded : True (len=164)

## 2. Config + run helper

We start from a copy of the current `SIM_CONFIG` (so every default is inherited, including the new
`reach_targeting_a/_b='random'`) and override only the smoke knobs. Crucially we pin
`memory={'day0_anchor':{'ttl_days':1}}` to match the production / `tier1` canon.

In [2]:
N_CITIZENS  = 24
RANDOM_SEED = 42
YEAR        = 2026

# 3 alternating package-mode days; P-A/P-B order flips each day; C (peer) always last.
DAYS = [
    {'phases': ['P-A', 'P-B', 'C']},
    {'phases': ['P-B', 'P-A', 'C']},
    {'phases': ['P-A', 'P-B', 'C']},
]

DATA = load('../data/yougov_survey_data/YouGovProcessedData.csv')


def make_config(**overrides):
    cfg = dict(SIM_CONFIG)
    cfg.update(
        n_citizens=N_CITIZENS,
        days=DAYS,
        k_peers_per_day=2,
        communication_mode='package',
        day0_anchor='ground_truth_with_rationale',
        memory={'day0_anchor': {'ttl_days': 1}},   # production canon: anchor trails off after Day 1
        thinking=False,
        llm_provider=PROVIDER,       # openai
        llm_model=MODEL,             # gpt-5-mini
        random_seed=RANDOM_SEED,
    )
    cfg.update(overrides)
    return cfg


def run_and_save(overrides, outdir):
    """Fresh nation -> run -> write CSVs + plots + config.json to a FIXED dir."""
    data = DATA.sample(n=N_CITIZENS, random_state=RANDOM_SEED).reset_index(drop=True)
    nation = build_nation(data, year=YEAR)
    cfg = make_config(**overrides)
    results = run_simulation(cfg, nation)
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    _write_all_csvs(out, results)
    save_result_plots(results, out)
    _atomic_write_json(_serialise_config(results['config']), out / 'config.json')
    print(f'\nSaved run to {out}')
    return out, results


print('reach_targeting defaults in SIM_CONFIG:',
      SIM_CONFIG.get('reach_targeting_a'), SIM_CONFIG.get('reach_targeting_b'))
print(f'n={N_CITIZENS}, days={len(DAYS)}, memory=ttl_days:1, thinking=False, model={MODEL}')

2026-07-05 20:54:10,995 [INFO] Columns with NaN counts (before filtering):
tprofile_gross_household    398
Political_Left_Right          6
dtype: int64
2026-07-05 20:54:10,996 [INFO] Column with most NaNs: tprofile_gross_household (398 NaNs)
2026-07-05 20:54:11,002 [INFO] 1483 rows after filtering.

reach_targeting defaults in SIM_CONFIG: random random
n=24, days=3, memory=ttl_days:1, thinking=False, model=gpt-5-mini

## 3. Run A - persuadable targeting (stochastic-block network)

Throttle side A to `reach_a=0.4` and target the **undecided**. Moderate reach so the reached set is
a strict subset of the audience (targeting has something to bite on).

In [3]:
OUT_A, res_a = run_and_save(
    {'reach_a': 0.4, 'reach_targeting_a': 'persuadable'},
    '../data/output/smoke/nb42_persuadable',
)

2026-07-05 20:55:13,054 [INFO] ===============================================================================
2026-07-05 20:55:13,054 [INFO]                             EXPERIMENT CONFIG
2026-07-05 20:55:13,055 [INFO] ===============================================================================
2026-07-05 20:55:13,056 [INFO] [run-shape]  n_citizens=24  days=3  seed=42  communication_mode=package
2026-07-05 20:55:13,056 [INFO] [exposure]   mode=rule_affinity_rank  targets=None  weights=None  audience_cap=None
2026-07-05 20:55:13,057 [INFO] [broadcast]  reach_a=0.40  reach_b=1.00  targeting_a=persuadable  targeting_b=random  message_source=offline  message_set=v1
2026-07-05 20:55:13,058 [INFO] [peer]       k_peers_per_day=2  network_type=stochastic_block  params={p_intra=0.15, p_inter=0.05}
2026-07-05 20:55:13,058 [INFO] [day0]       anchor=ground_truth_with_rationale
2026-07-05 20:55:13,059 [INFO] [memory]     preset=custom  verbatim_window_days=2  anchor=on(ttl=1)  own_reasoning=on  daily_summaries=on  reflections=on  traj=off
2026-07-05 20:55:13,059 [INFO] [memory]     stage_overrides: none
2026-07-05 20:55:13,060 [INFO] [llm]        provider=openai  model=gpt-5-mini  temp=0.5  thinking=False
2026-07-05 20:55:13,060 [INFO] [survey-llm] same as [llm]
2026-07-05 20:55:13,061 [INFO] [package]    6 of 6 policies: all
2026-07-05 20:55:13,061 [INFO] [runtime]    checkpoint_dir=off  resume=False
2026-07-05 20:55:13,062 [INFO] ===============================================================================
2026-07-05 20:55:13,069 [INFO] Loaded offline message pool 'v1': 14 cells, 280 messages, 24 sources (seed=42)
2026-07-05 20:55:13,071 [WARNING] Small population (n=24): 2-block SBM is unreliable. Bumping p_inter 0.050 -> 0.100. Consider n>=50 or network_type='barabasi_albert'.
2026-07-05 20:55:13,075 [INFO] Network: n_nodes=24, n_edges=36, n_components=1, mean_degree=3.00, auto_connected_edges=0
2026-07-05 20:55:13,076 [INFO] Reach subsample: agent_a audience 6/15 (reach=0.4, targeting=persuadable)  |GT| kept=0.889 dropped=2.037
2026-07-05 20:55:13,077 [INFO] Reach subsample: agent_b audience 15/15 (reach=1.0, targeting=random)
2026-07-05 20:55:13,078 [INFO] Persona mode: 'real' applied to 24 agents (seed=42)
2026-07-05 20:55:13,079 [INFO] Simulation: 24 agents, 3 days
2026-07-05 20:55:13,080 [INFO] Running package baseline survey (day 0), policies=['ClimatePolicyID(1)', 'ClimatePolicyID(2)', 'ClimatePolicyID(3)', 'ClimatePolicyID(4)', 'ClimatePolicyID(5)', 'ClimatePolicyID(6)'], anchor=ground_truth_with_rationale
2026-07-05 20:55:15,579 [WARNING] OpenAI: model does not support 'temperature', retrying without it
2026-07-05 21:00:13,895 [INFO] Day 0 mean package index: +0.69
2026-07-05 21:00:13,896 [INFO] --- Day 1/3 (package=climate_policy_package, phases=['P-A', 'P-B', 'C']) ---
2026-07-05 21:01:00,943 [INFO] [P-A] Day 1: delivered package message to 6 citizens. Message (first 120 chars): Every new solar roof, onshore wind project and offshore array is a small piece of insurance against the next price shock...
2026-07-05 21:01:00,944 [INFO] [P-A] Sample package reflection: Accelerate the roll-out of renewable energy production (e.g. more offshore and onshore wind parks)
- Somewhat support. I like the insurance argument in the message — more renewables can help shield us...
2026-07-05 21:02:49,176 [INFO] [P-B] Day 1: delivered package message to 15 citizens. Message (first 120 chars): Net Zero subsidies have become a multi-billion-pound transfer from struggling families to a sheltered renewables industr...
2026-07-05 21:02:49,178 [INFO] [P-B] Sample package reflection: - Accelerate the roll-out of renewable energy production (e.g. more offshore and onshore wind parks)
Somewhat support. The message’s claim that subsidies are a huge transfer to industry worries me, an...
2026-07-05 21:05:00,874 [INFO] [C] Day 1: 24 citizens generated package messages, 22 citizens reflected.
2026-07-05 21:05:00,875 [INFO] [C] Sample package message: I’m broadly in favour of more renewables — they feel like useful insurance against volatile gas prices so I somewhat support expanding well‑sited wind with proper local consultation and support for wo...
2026-07-05 21:05:00,876 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(3), day 1
2026-07-05 21:05:03,790 [INFO] Agent 165.0: F (+2), previous=0, shift=+2
2026-07-05 21:05:06,983 [INFO] Agent 582.0: B (-2), previous=-2, shift=+0
2026-07-05 21:05:09,862 [INFO] Agent 1379.0: C (-1), previous=-1, shift=+0
2026-07-05 21:05:12,706 [INFO] Agent 713.0: A (-3), previous=-3, shift=+0
2026-07-05 21:05:15,633 [INFO] Agent 1878.0: E (+1), previous=0, shift=+1
2026-07-05 21:05:18,874 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 21:05:22,030 [INFO] Agent 409.0: E (+1), previous=1, shift=+0
2026-07-05 21:05:25,474 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:05:27,737 [INFO] Agent 91.0: E (+1), previous=1, shift=+0
2026-07-05 21:05:30,396 [INFO] Agent 69.0: F (+2), previous=0, shift=+2
2026-07-05 21:05:33,387 [INFO] Agent 166.0: E (+1), previous=1, shift=+0
2026-07-05 21:05:36,478 [INFO] Agent 103.0: B (-2), previous=-2, shift=+0
2026-07-05 21:05:40,599 [INFO] Agent 1262.0: B (-2), previous=-3, shift=+1
2026-07-05 21:05:43,502 [INFO] Agent 377.0: C (-1), previous=-1, shift=+0
2026-07-05 21:05:46,437 [INFO] Agent 574.0: E (+1), previous=1, shift=+0
2026-07-05 21:05:49,484 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:05:52,451 [INFO] Agent 752.0: A (-3), previous=-3, shift=+0
2026-07-05 21:05:56,042 [INFO] Agent 1001.0: B (-2), previous=-2, shift=+0
2026-07-05 21:05:58,542 [INFO] Agent 440.0: E (+1), previous=1, shift=+0
2026-07-05 21:06:01,220 [INFO] Agent 1250.0: A (-3), previous=-3, shift=+0
2026-07-05 21:06:03,848 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 21:06:06,769 [INFO] Agent 1904.0: A (-3), previous=-3, shift=+0
2026-07-05 21:06:09,757 [INFO] Agent 1900.0: C (-1), previous=0, shift=-1
2026-07-05 21:06:12,887 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 21:06:12,889 [INFO] Mean shift: +0.21
2026-07-05 21:06:12,890 [INFO] Shift distribution:
shift
-1     1
 0    19
 1     2
 2     2
2026-07-05 21:06:12,891 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(5), day 1
2026-07-05 21:06:15,865 [INFO] Agent 165.0: E (+1), previous=1, shift=+0
2026-07-05 21:06:18,631 [INFO] Agent 582.0: F (+2), previous=0, shift=+2
2026-07-05 21:06:21,563 [INFO] Agent 1379.0: F (+2), previous=0, shift=+2
2026-07-05 21:06:24,355 [INFO] Agent 713.0: B (-2), previous=-2, shift=+0
2026-07-05 21:06:27,150 [INFO] Agent 1878.0: F (+2), previous=2, shift=+0
2026-07-05 21:06:30,340 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 21:06:33,441 [INFO] Agent 409.0: E (+1), previous=1, shift=+0
2026-07-05 21:06:37,918 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:06:40,556 [INFO] Agent 91.0: F (+2), previous=2, shift=+0
2026-07-05 21:07:44,443 [INFO] Agent 69.0: F (+2), previous=0, shift=+2
2026-07-05 21:07:47,481 [INFO] Agent 166.0: F (+2), previous=0, shift=+2
2026-07-05 21:07:50,448 [INFO] Agent 103.0: G (+3), previous=3, shift=+0
2026-07-05 21:07:53,491 [INFO] Agent 1262.0: F (+2), previous=0, shift=+2
2026-07-05 21:07:56,438 [INFO] Agent 377.0: E (+1), previous=1, shift=+0
2026-07-05 21:07:59,593 [INFO] Agent 574.0: E (+1), previous=1, shift=+0
2026-07-05 21:08:02,636 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:08:07,492 [INFO] Agent 752.0: B (-2), previous=-2, shift=+0
2026-07-05 21:08:10,550 [INFO] Agent 1001.0: F (+2), previous=0, shift=+2
2026-07-05 21:08:13,619 [INFO] Agent 440.0: B (-2), previous=-2, shift=+0
2026-07-05 21:08:16,649 [INFO] Agent 1250.0: F (+2), previous=1, shift=+1
2026-07-05 21:08:20,297 [INFO] Agent 355.0: F (+2), previous=2, shift=+0
2026-07-05 21:08:23,624 [INFO] Agent 1904.0: A (-3), previous=-3, shift=+0
2026-07-05 21:08:26,800 [INFO] Agent 1900.0: E (+1), previous=-1, shift=+2
2026-07-05 21:08:29,739 [INFO] Agent 620.0: D (+0), previous=0, shift=+0
2026-07-05 21:08:29,741 [INFO] Mean shift: +0.62
2026-07-05 21:08:29,743 [INFO] Shift distribution:
shift
0    16
1     1
2     7
2026-07-05 21:08:29,744 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(4), day 1
2026-07-05 21:08:33,013 [INFO] Agent 165.0: E (+1), previous=1, shift=+0
2026-07-05 21:08:36,158 [INFO] Agent 582.0: F (+2), previous=2, shift=+0
2026-07-05 21:08:39,645 [INFO] Agent 1379.0: F (+2), previous=0, shift=+2
2026-07-05 21:08:42,462 [INFO] Agent 713.0: A (-3), previous=-3, shift=+0
2026-07-05 21:08:45,640 [INFO] Agent 1878.0: E (+1), previous=1, shift=+0
2026-07-05 21:08:48,942 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 21:08:53,460 [INFO] Agent 409.0: G (+3), previous=3, shift=+0
2026-07-05 21:08:56,488 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:08:59,757 [INFO] Agent 91.0: F (+2), previous=2, shift=+0
2026-07-05 21:09:02,895 [INFO] Agent 69.0: F (+2), previous=1, shift=+1
2026-07-05 21:09:10,629 [INFO] Agent 166.0: E (+1), previous=1, shift=+0
2026-07-05 21:09:13,575 [INFO] Agent 103.0: F (+2), previous=3, shift=-1
2026-07-05 21:09:16,537 [INFO] Agent 1262.0: F (+2), previous=1, shift=+1
2026-07-05 21:09:19,678 [INFO] Agent 377.0: G (+3), previous=3, shift=+0
2026-07-05 21:09:22,664 [INFO] Agent 574.0: G (+3), previous=3, shift=+0
2026-07-05 21:09:25,991 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:09:28,912 [INFO] Agent 752.0: F (+2), previous=2, shift=+0
2026-07-05 21:09:31,735 [INFO] Agent 1001.0: G (+3), previous=3, shift=+0
2026-07-05 21:09:35,170 [INFO] Agent 440.0: G (+3), previous=3, shift=+0
2026-07-05 21:09:39,098 [INFO] Agent 1250.0: F (+2), previous=3, shift=-1
2026-07-05 21:09:42,528 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 21:09:45,486 [INFO] Agent 1904.0: F (+2), previous=0, shift=+2
2026-07-05 21:09:48,722 [INFO] Agent 1900.0: E (+1), previous=1, shift=+0
2026-07-05 21:09:51,523 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 21:09:51,525 [INFO] Mean shift: +0.17
2026-07-05 21:09:51,527 [INFO] Shift distribution:
shift
-1     2
 0    18
 1     2
 2     2
2026-07-05 21:09:51,528 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(1), day 1
2026-07-05 21:09:54,970 [INFO] Agent 165.0: F (+2), previous=2, shift=+0
2026-07-05 21:09:58,041 [INFO] Agent 582.0: F (+2), previous=1, shift=+1
2026-07-05 21:10:00,975 [INFO] Agent 1379.0: F (+2), previous=2, shift=+0
2026-07-05 21:10:04,107 [INFO] Agent 713.0: E (+1), previous=1, shift=+0
2026-07-05 21:10:07,919 [INFO] Agent 1878.0: E (+1), previous=2, shift=-1
2026-07-05 21:10:10,909 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 21:10:14,066 [INFO] Agent 409.0: F (+2), previous=2, shift=+0
2026-07-05 21:10:17,025 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:10:19,862 [INFO] Agent 91.0: F (+2), previous=2, shift=+0
2026-07-05 21:10:22,982 [INFO] Agent 69.0: F (+2), previous=1, shift=+1
2026-07-05 21:10:27,721 [INFO] Agent 166.0: G (+3), previous=3, shift=+0
2026-07-05 21:10:31,792 [INFO] Agent 103.0: G (+3), previous=3, shift=+0
2026-07-05 21:10:34,650 [INFO] Agent 1262.0: F (+2), previous=1, shift=+1
2026-07-05 21:10:37,662 [INFO] Agent 377.0: G (+3), previous=3, shift=+0
2026-07-05 21:10:41,855 [INFO] Agent 574.0: F (+2), previous=2, shift=+0
2026-07-05 21:10:45,043 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:10:48,668 [INFO] Agent 752.0: F (+2), previous=0, shift=+2
2026-07-05 21:10:57,194 [INFO] Agent 1001.0: E (+1), previous=1, shift=+0
2026-07-05 21:11:00,625 [INFO] Agent 440.0: G (+3), previous=3, shift=+0
2026-07-05 21:11:03,880 [INFO] Agent 1250.0: F (+2), previous=2, shift=+0
2026-07-05 21:11:07,542 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 21:11:10,940 [INFO] Agent 1904.0: F (+2), previous=1, shift=+1
2026-07-05 21:11:14,266 [INFO] Agent 1900.0: E (+1), previous=1, shift=+0
2026-07-05 21:11:17,532 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 21:11:17,534 [INFO] Mean shift: +0.21
2026-07-05 21:11:17,536 [INFO] Shift distribution:
shift
-1     1
 0    18
 1     4
 2     1
2026-07-05 21:11:17,537 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(2), day 1
2026-07-05 21:11:20,652 [INFO] Agent 165.0: F (+2), previous=0, shift=+2
2026-07-05 21:11:24,259 [INFO] Agent 582.0: B (-2), previous=0, shift=-2
2026-07-05 21:11:27,356 [INFO] Agent 1379.0: C (-1), previous=0, shift=-1
2026-07-05 21:11:30,745 [INFO] Agent 713.0: A (-3), previous=-3, shift=+0
2026-07-05 21:11:33,890 [INFO] Agent 1878.0: C (-1), previous=-1, shift=+0
2026-07-05 21:11:38,123 [INFO] Agent 844.0: F (+2), previous=2, shift=+0
2026-07-05 21:11:41,239 [INFO] Agent 409.0: F (+2), previous=2, shift=+0
2026-07-05 21:11:44,379 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:11:47,750 [INFO] Agent 91.0: E (+1), previous=1, shift=+0
2026-07-05 21:11:51,846 [INFO] Agent 69.0: F (+2), previous=0, shift=+2
2026-07-05 21:11:55,391 [INFO] Agent 166.0: G (+3), previous=3, shift=+0
2026-07-05 21:11:58,262 [INFO] Agent 103.0: F (+2), previous=-2, shift=+4
2026-07-05 21:12:01,742 [INFO] Agent 1262.0: B (-2), previous=0, shift=-2
2026-07-05 21:12:05,141 [INFO] Agent 377.0: F (+2), previous=2, shift=+0
2026-07-05 21:12:08,897 [INFO] Agent 574.0: F (+2), previous=0, shift=+2
2026-07-05 21:12:13,368 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:12:16,557 [INFO] Agent 752.0: B (-2), previous=-2, shift=+0
2026-07-05 21:12:19,371 [INFO] Agent 1001.0: F (+2), previous=2, shift=+0
2026-07-05 21:12:22,928 [INFO] Agent 440.0: G (+3), previous=3, shift=+0
2026-07-05 21:12:25,812 [INFO] Agent 1250.0: F (+2), previous=0, shift=+2
2026-07-05 21:12:28,809 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 21:12:31,697 [INFO] Agent 1904.0: B (-2), previous=-1, shift=-1
2026-07-05 21:12:34,972 [INFO] Agent 1900.0: E (+1), previous=0, shift=+1
2026-07-05 21:12:38,247 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 21:12:38,248 [INFO] Mean shift: +0.29
2026-07-05 21:12:38,250 [INFO] Shift distribution:
shift
-2     2
-1     2
 0    14
 1     1
 2     4
 4     1
2026-07-05 21:12:38,251 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(6), day 1
2026-07-05 21:12:41,392 [INFO] Agent 165.0: E (+1), previous=1, shift=+0
2026-07-05 21:12:47,683 [INFO] Agent 582.0: C (-1), previous=-1, shift=+0
2026-07-05 21:12:51,162 [INFO] Agent 1379.0: E (+1), previous=1, shift=+0
2026-07-05 21:12:53,718 [INFO] Agent 713.0: A (-3), previous=-3, shift=+0
2026-07-05 21:12:57,132 [INFO] Agent 1878.0: E (+1), previous=0, shift=+1
2026-07-05 21:12:59,966 [INFO] Agent 844.0: B (-2), previous=-2, shift=+0
2026-07-05 21:13:03,021 [INFO] Agent 409.0: F (+2), previous=2, shift=+0
2026-07-05 21:13:06,189 [INFO] Agent 1957.0: E (+1), previous=1, shift=+0
2026-07-05 21:13:09,153 [INFO] Agent 91.0: F (+2), previous=0, shift=+2
2026-07-05 21:13:11,953 [INFO] Agent 69.0: B (-2), previous=-2, shift=+0
2026-07-05 21:13:15,439 [INFO] Agent 166.0: E (+1), previous=1, shift=+0
2026-07-05 21:13:18,227 [INFO] Agent 103.0: B (-2), previous=-3, shift=+1
2026-07-05 21:13:21,372 [INFO] Agent 1262.0: F (+2), previous=-2, shift=+4
2026-07-05 21:13:24,517 [INFO] Agent 377.0: F (+2), previous=0, shift=+2
2026-07-05 21:13:27,436 [INFO] Agent 574.0: F (+2), previous=0, shift=+2
2026-07-05 21:13:30,420 [INFO] Agent 556.0: E (+1), previous=1, shift=+0
2026-07-05 21:13:33,221 [INFO] Agent 752.0: B (-2), previous=-2, shift=+0
2026-07-05 21:13:35,953 [INFO] Agent 1001.0: C (-1), previous=-1, shift=+0
2026-07-05 21:13:39,064 [INFO] Agent 440.0: E (+1), previous=1, shift=+0
2026-07-05 21:13:41,694 [INFO] Agent 1250.0: F (+2), previous=1, shift=+1
2026-07-05 21:13:44,964 [INFO] Agent 355.0: F (+2), previous=2, shift=+0
2026-07-05 21:13:48,016 [INFO] Agent 1904.0: B (-2), previous=-3, shift=+1
2026-07-05 21:13:50,797 [INFO] Agent 1900.0: E (+1), previous=2, shift=-1
2026-07-05 21:13:54,796 [INFO] Agent 620.0: F (+2), previous=0, shift=+2
2026-07-05 21:13:54,798 [INFO] Mean shift: +0.62
2026-07-05 21:13:54,809 [INFO] Shift distribution:
shift
-1     1
 0    14
 1     4
 2     4
 4     1
2026-07-05 21:13:54,810 [INFO] Day 1 mean package index: +1.04
2026-07-05 21:13:54,810 [INFO] --- Day 2/3 (package=climate_policy_package, phases=['P-B', 'P-A', 'C']) ---
2026-07-05 21:15:40,697 [INFO] [P-B] Day 2: delivered package message to 15 citizens. Message (first 120 chars): A common-sense plan for cheap power has three steps: remove the carbon tax from generation, end the Renewable Obligation...
2026-07-05 21:15:40,697 [INFO] [P-B] Sample package reflection: Accelerate the roll-out of renewable energy production (e.g. more offshore and onshore wind parks)
- Somewhat support. I like the insurance argument that more renewables can shield us from internation...
2026-07-05 21:16:23,911 [INFO] [P-A] Day 2: delivered package message to 6 citizens. Message (first 120 chars): Communities should share directly in the benefits of nearby renewable projects through lower bills, community ownership ...
2026-07-05 21:16:23,912 [INFO] [P-A] Sample package reflection: Accelerate the roll-out of renewable energy production (e.g. more offshore and onshore wind parks)
- Somewhat support. I like the “communities should share directly” line — community ownership, local ...
2026-07-05 21:18:36,529 [INFO] [C] Day 2: 24 citizens generated package messages, 24 citizens reflected.
2026-07-05 21:18:36,530 [INFO] [C] Sample package message: I’d somewhat support accelerating renewables if projects are well‑sited, include local consultation and community benefits so costs and visual impacts don’t fall unfairly on households. I’m cautiously...
2026-07-05 21:18:36,531 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(1), day 2
2026-07-05 21:18:39,613 [INFO] Agent 165.0: F (+2), previous=2, shift=+0
2026-07-05 21:18:45,381 [INFO] Agent 582.0: F (+2), previous=2, shift=+0
2026-07-05 21:18:53,484 [INFO] Agent 1379.0: F (+2), previous=2, shift=+0
2026-07-05 21:18:56,394 [INFO] Agent 713.0: E (+1), previous=1, shift=+0
2026-07-05 21:18:59,267 [INFO] Agent 1878.0: E (+1), previous=1, shift=+0
2026-07-05 21:19:03,208 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 21:19:06,361 [INFO] Agent 409.0: F (+2), previous=2, shift=+0
2026-07-05 21:19:09,247 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:19:12,532 [INFO] Agent 91.0: F (+2), previous=2, shift=+0
2026-07-05 21:19:15,809 [INFO] Agent 69.0: F (+2), previous=2, shift=+0
2026-07-05 21:19:18,946 [INFO] Agent 166.0: G (+3), previous=3, shift=+0
2026-07-05 21:19:22,331 [INFO] Agent 103.0: G (+3), previous=3, shift=+0
2026-07-05 21:19:25,784 [INFO] Agent 1262.0: F (+2), previous=2, shift=+0
2026-07-05 21:19:28,806 [INFO] Agent 377.0: G (+3), previous=3, shift=+0
2026-07-05 21:19:31,659 [INFO] Agent 574.0: F (+2), previous=2, shift=+0
2026-07-05 21:19:34,555 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:19:37,679 [INFO] Agent 752.0: F (+2), previous=2, shift=+0
2026-07-05 21:19:40,977 [INFO] Agent 1001.0: E (+1), previous=1, shift=+0
2026-07-05 21:19:44,011 [INFO] Agent 440.0: G (+3), previous=3, shift=+0
2026-07-05 21:19:48,956 [INFO] Agent 1250.0: F (+2), previous=2, shift=+0
2026-07-05 21:19:51,801 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 21:19:54,606 [INFO] Agent 1904.0: F (+2), previous=2, shift=+0
2026-07-05 21:19:57,597 [INFO] Agent 1900.0: E (+1), previous=1, shift=+0
2026-07-05 21:20:00,877 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 21:20:00,879 [INFO] Mean shift: +0.00
2026-07-05 21:20:00,881 [INFO] Shift distribution:
shift
0    24
2026-07-05 21:20:00,882 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(3), day 2
2026-07-05 21:20:04,625 [INFO] Agent 165.0: F (+2), previous=2, shift=+0

Saved run to ../data/output/smoke/nb42_persuadable

### Verify Feature 1 - persuadable kept the undecided

`targeting_diagnostics.csv` compares the reached audience vs the dropped audience on mean
`|ground-truth package index|`. Persuadable targeting should keep the *smaller* `|GT|`.

In [4]:
td = pd.read_csv(OUT_A / 'targeting_diagnostics.csv')
display(td)

row = td[td['side'] == 'A'].iloc[0]
print(f"side A: targeting={row['targeting_mode']}, reach={row['reach']}, "
      f"reached |GT|={row['reached_mean_absgt']:.3f} vs dropped |GT|={row['dropped_mean_absgt']:.3f}")
assert row['reached_mean_absgt'] < row['dropped_mean_absgt'], \
    'FAIL: persuadable did not keep the more-undecided audience'
print('PASS: persuadable targeting kept the undecided (lower |GT|).')

attrs_a = pd.read_csv(OUT_A / 'agent_attributes.csv')
print('\nReached-by counts per bucket:')
print(attrs_a.groupby('political_exposure')[['reached_by_a', 'reached_by_b']].sum())

,side,targeting_mode,reach,n_audience,n_reached,n_dropped,reached_mean_absgt,dropped_mean_absgt
0,A,persuadable,0.4,15,6,9,0.888889,2.037037
1,B,random,1.0,15,15,0,1.444444,NaN

side A: targeting=persuadable, reach=0.4, reached |GT|=0.889 vs dropped |GT|=2.037
PASS: persuadable targeting kept the undecided (lower |GT|).

Reached-by counts per bucket:
                    reached_by_a  reached_by_b
political_exposure
A-only                         0             0
B-only                         0             1
both                           6            14
neither                        0             0

## 4. Run B - degree centrality targeting (Barabasi-Albert network)

BA has hubs, so degree centrality varies. Throttle side A to `reach_a=0.4` and target the
highest-degree audience members.

In [5]:
OUT_B, res_b = run_and_save(
    {'reach_a': 0.4, 'reach_targeting_a': 'degree',
     'network_type': 'barabasi_albert', 'network_params': {'m': 3}},
    '../data/output/smoke/nb42_degree',
)

2026-07-05 21:45:16,806 [INFO] ===============================================================================
2026-07-05 21:45:16,807 [INFO]                             EXPERIMENT CONFIG
2026-07-05 21:45:16,808 [INFO] ===============================================================================
2026-07-05 21:45:16,809 [INFO] [run-shape]  n_citizens=24  days=3  seed=42  communication_mode=package
2026-07-05 21:45:16,809 [INFO] [exposure]   mode=rule_affinity_rank  targets=None  weights=None  audience_cap=None
2026-07-05 21:45:16,810 [INFO] [broadcast]  reach_a=0.40  reach_b=1.00  targeting_a=degree  targeting_b=random  message_source=offline  message_set=v1
2026-07-05 21:45:16,810 [INFO] [peer]       k_peers_per_day=2  network_type=barabasi_albert  params={m=3}
2026-07-05 21:45:16,811 [INFO] [day0]       anchor=ground_truth_with_rationale
2026-07-05 21:45:16,812 [INFO] [memory]     preset=custom  verbatim_window_days=2  anchor=on(ttl=1)  own_reasoning=on  daily_summaries=on  reflections=on  traj=off
2026-07-05 21:45:16,812 [INFO] [memory]     stage_overrides: none
2026-07-05 21:45:16,813 [INFO] [llm]        provider=openai  model=gpt-5-mini  temp=0.5  thinking=False
2026-07-05 21:45:16,813 [INFO] [survey-llm] same as [llm]
2026-07-05 21:45:16,814 [INFO] [package]    6 of 6 policies: all
2026-07-05 21:45:16,814 [INFO] [runtime]    checkpoint_dir=off  resume=False
2026-07-05 21:45:16,815 [INFO] ===============================================================================
2026-07-05 21:45:16,825 [INFO] Loaded offline message pool 'v1': 14 cells, 280 messages, 24 sources (seed=42)
2026-07-05 21:45:16,827 [INFO] Network: n_nodes=24, n_edges=63, n_components=1, mean_degree=5.25, auto_connected_edges=0
2026-07-05 21:45:16,828 [INFO] Reach subsample: agent_a audience 6/15 (reach=0.4, targeting=degree)  degree kept=0.399 dropped=0.159
2026-07-05 21:45:16,829 [INFO] Reach subsample: agent_b audience 15/15 (reach=1.0, targeting=random)
2026-07-05 21:45:16,830 [INFO] Persona mode: 'real' applied to 24 agents (seed=42)
2026-07-05 21:45:16,831 [INFO] Simulation: 24 agents, 3 days
2026-07-05 21:45:16,832 [INFO] Running package baseline survey (day 0), policies=['ClimatePolicyID(1)', 'ClimatePolicyID(2)', 'ClimatePolicyID(3)', 'ClimatePolicyID(4)', 'ClimatePolicyID(5)', 'ClimatePolicyID(6)'], anchor=ground_truth_with_rationale
2026-07-05 21:50:20,123 [INFO] Day 0 mean package index: +0.69
2026-07-05 21:50:20,124 [INFO] --- Day 1/3 (package=climate_policy_package, phases=['P-A', 'P-B', 'C']) ---
2026-07-05 21:51:00,126 [INFO] [P-A] Day 1: delivered package message to 6 citizens. Message (first 120 chars): Every new solar roof, onshore wind project and offshore array is a small piece of insurance against the next price shock...
2026-07-05 21:51:00,127 [INFO] [P-A] Sample package reflection: - Accelerate the roll-out of renewable energy production (e.g. more offshore and onshore wind parks): Somewhat support. I like the “insurance against the next price shock” framing — more renewables ca...
2026-07-05 21:52:36,849 [INFO] [P-B] Day 1: delivered package message to 15 citizens. Message (first 120 chars): Net Zero subsidies have become a multi-billion-pound transfer from struggling families to a sheltered renewables industr...
2026-07-05 21:52:36,850 [INFO] [P-B] Sample package reflection: - Accelerate the roll-out of renewable energy production (e.g. more offshore and onshore wind parks): Somewhat support. The message worries me about subsidies and costs, but I still find the argument ...
2026-07-05 21:54:44,492 [INFO] [C] Day 1: 24 citizens generated package messages, 20 citizens reflected.
2026-07-05 21:54:44,492 [INFO] [C] Sample package message: I generally support accelerating renewables — they feel like good long-term insurance against price shocks and cleaner local air, though I’d want careful siting and community compensation. I somewhat ...
2026-07-05 21:54:44,493 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(3), day 1
2026-07-05 21:54:47,376 [INFO] Agent 165.0: F (+2), previous=0, shift=+2
2026-07-05 21:54:50,375 [INFO] Agent 582.0: F (+2), previous=-2, shift=+4
2026-07-05 21:54:53,282 [INFO] Agent 1379.0: C (-1), previous=-1, shift=+0
2026-07-05 21:54:57,031 [INFO] Agent 713.0: A (-3), previous=-3, shift=+0
2026-07-05 21:54:59,649 [INFO] Agent 1878.0: F (+2), previous=0, shift=+2
2026-07-05 21:55:03,107 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 21:55:06,542 [INFO] Agent 409.0: E (+1), previous=1, shift=+0
2026-07-05 21:55:09,816 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:55:13,198 [INFO] Agent 91.0: E (+1), previous=1, shift=+0
2026-07-05 21:55:15,940 [INFO] Agent 69.0: F (+2), previous=0, shift=+2
2026-07-05 21:55:19,056 [INFO] Agent 166.0: E (+1), previous=1, shift=+0
2026-07-05 21:55:22,107 [INFO] Agent 103.0: B (-2), previous=-2, shift=+0
2026-07-05 21:55:25,135 [INFO] Agent 1262.0: B (-2), previous=-3, shift=+1
2026-07-05 21:55:27,953 [INFO] Agent 377.0: C (-1), previous=-1, shift=+0
2026-07-05 21:55:30,500 [INFO] Agent 574.0: E (+1), previous=1, shift=+0
2026-07-05 21:55:35,791 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:55:38,593 [INFO] Agent 752.0: A (-3), previous=-3, shift=+0
2026-07-05 21:55:41,396 [INFO] Agent 1001.0: B (-2), previous=-2, shift=+0
2026-07-05 21:55:44,342 [INFO] Agent 440.0: E (+1), previous=1, shift=+0
2026-07-05 21:55:47,364 [INFO] Agent 1250.0: B (-2), previous=-3, shift=+1
2026-07-05 21:55:50,651 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 21:55:53,660 [INFO] Agent 1904.0: B (-2), previous=-3, shift=+1
2026-07-05 21:55:56,409 [INFO] Agent 1900.0: F (+2), previous=0, shift=+2
2026-07-05 21:56:00,040 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 21:56:00,041 [INFO] Mean shift: +0.62
2026-07-05 21:56:00,043 [INFO] Shift distribution:
shift
0    16
1     3
2     4
4     1
2026-07-05 21:56:00,044 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(5), day 1
2026-07-05 21:56:02,871 [INFO] Agent 165.0: E (+1), previous=1, shift=+0
2026-07-05 21:56:06,016 [INFO] Agent 582.0: F (+2), previous=0, shift=+2
2026-07-05 21:56:09,830 [INFO] Agent 1379.0: F (+2), previous=0, shift=+2
2026-07-05 21:56:13,518 [INFO] Agent 713.0: B (-2), previous=-2, shift=+0
2026-07-05 21:56:16,319 [INFO] Agent 1878.0: F (+2), previous=2, shift=+0
2026-07-05 21:56:20,303 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 21:56:23,263 [INFO] Agent 409.0: E (+1), previous=1, shift=+0
2026-07-05 21:56:26,321 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:56:30,178 [INFO] Agent 91.0: F (+2), previous=2, shift=+0
2026-07-05 21:56:33,296 [INFO] Agent 69.0: F (+2), previous=0, shift=+2
2026-07-05 21:56:36,558 [INFO] Agent 166.0: F (+2), previous=0, shift=+2
2026-07-05 21:56:40,229 [INFO] Agent 103.0: G (+3), previous=3, shift=+0
2026-07-05 21:56:43,773 [INFO] Agent 1262.0: F (+2), previous=0, shift=+2
2026-07-05 21:56:47,568 [INFO] Agent 377.0: E (+1), previous=1, shift=+0
2026-07-05 21:56:51,859 [INFO] Agent 574.0: E (+1), previous=1, shift=+0
2026-07-05 21:56:54,751 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:56:57,953 [INFO] Agent 752.0: B (-2), previous=-2, shift=+0
2026-07-05 21:57:01,198 [INFO] Agent 1001.0: F (+2), previous=0, shift=+2
2026-07-05 21:57:04,230 [INFO] Agent 440.0: B (-2), previous=-2, shift=+0
2026-07-05 21:57:07,489 [INFO] Agent 1250.0: F (+2), previous=1, shift=+1
2026-07-05 21:57:10,374 [INFO] Agent 355.0: F (+2), previous=2, shift=+0
2026-07-05 21:57:13,553 [INFO] Agent 1904.0: B (-2), previous=-3, shift=+1
2026-07-05 21:57:17,218 [INFO] Agent 1900.0: B (-2), previous=-1, shift=-1
2026-07-05 21:57:20,828 [INFO] Agent 620.0: E (+1), previous=0, shift=+1
2026-07-05 21:57:20,830 [INFO] Mean shift: +0.58
2026-07-05 21:57:20,831 [INFO] Shift distribution:
shift
-1     1
 0    14
 1     3
 2     6
2026-07-05 21:57:20,832 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(4), day 1
2026-07-05 21:57:24,167 [INFO] Agent 165.0: E (+1), previous=1, shift=+0
2026-07-05 21:57:27,176 [INFO] Agent 582.0: F (+2), previous=2, shift=+0
2026-07-05 21:57:30,049 [INFO] Agent 1379.0: F (+2), previous=0, shift=+2
2026-07-05 21:57:33,198 [INFO] Agent 713.0: A (-3), previous=-3, shift=+0
2026-07-05 21:57:36,744 [INFO] Agent 1878.0: F (+2), previous=1, shift=+1
2026-07-05 21:57:39,748 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 21:57:43,247 [INFO] Agent 409.0: G (+3), previous=3, shift=+0
2026-07-05 21:57:46,062 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:57:48,909 [INFO] Agent 91.0: F (+2), previous=2, shift=+0
2026-07-05 21:57:51,921 [INFO] Agent 69.0: F (+2), previous=1, shift=+1
2026-07-05 21:57:55,199 [INFO] Agent 166.0: E (+1), previous=1, shift=+0
2026-07-05 21:57:58,870 [INFO] Agent 103.0: G (+3), previous=3, shift=+0
2026-07-05 21:58:01,809 [INFO] Agent 1262.0: F (+2), previous=1, shift=+1
2026-07-05 21:58:06,057 [INFO] Agent 377.0: G (+3), previous=3, shift=+0
2026-07-05 21:58:09,074 [INFO] Agent 574.0: G (+3), previous=3, shift=+0
2026-07-05 21:58:12,253 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:58:15,209 [INFO] Agent 752.0: F (+2), previous=2, shift=+0
2026-07-05 21:58:18,337 [INFO] Agent 1001.0: G (+3), previous=3, shift=+0
2026-07-05 21:58:21,186 [INFO] Agent 440.0: G (+3), previous=3, shift=+0
2026-07-05 21:58:25,084 [INFO] Agent 1250.0: F (+2), previous=3, shift=-1
2026-07-05 21:58:29,574 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 21:58:33,498 [INFO] Agent 1904.0: F (+2), previous=0, shift=+2
2026-07-05 21:58:37,008 [INFO] Agent 1900.0: F (+2), previous=1, shift=+1
2026-07-05 21:58:40,155 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 21:58:40,156 [INFO] Mean shift: +0.29
2026-07-05 21:58:40,158 [INFO] Shift distribution:
shift
-1     1
 0    17
 1     4
 2     2
2026-07-05 21:58:40,159 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(1), day 1
2026-07-05 21:58:43,432 [INFO] Agent 165.0: F (+2), previous=2, shift=+0
2026-07-05 21:58:47,221 [INFO] Agent 582.0: F (+2), previous=1, shift=+1
2026-07-05 21:58:50,151 [INFO] Agent 1379.0: F (+2), previous=2, shift=+0
2026-07-05 21:58:53,920 [INFO] Agent 713.0: E (+1), previous=1, shift=+0
2026-07-05 21:58:57,063 [INFO] Agent 1878.0: F (+2), previous=2, shift=+0
2026-07-05 21:59:00,208 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 21:59:03,684 [INFO] Agent 409.0: F (+2), previous=2, shift=+0
2026-07-05 21:59:07,276 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 21:59:10,776 [INFO] Agent 91.0: F (+2), previous=2, shift=+0
2026-07-05 21:59:13,729 [INFO] Agent 69.0: F (+2), previous=1, shift=+1
2026-07-05 21:59:16,855 [INFO] Agent 166.0: G (+3), previous=3, shift=+0
2026-07-05 21:59:23,143 [INFO] Agent 103.0: G (+3), previous=3, shift=+0
2026-07-05 21:59:26,612 [INFO] Agent 1262.0: F (+2), previous=1, shift=+1
2026-07-05 21:59:29,435 [INFO] Agent 377.0: F (+2), previous=3, shift=-1
2026-07-05 21:59:32,789 [INFO] Agent 574.0: F (+2), previous=2, shift=+0
2026-07-05 21:59:35,900 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 21:59:39,281 [INFO] Agent 752.0: F (+2), previous=0, shift=+2
2026-07-05 21:59:42,568 [INFO] Agent 1001.0: E (+1), previous=1, shift=+0
2026-07-05 21:59:48,191 [INFO] Agent 440.0: G (+3), previous=3, shift=+0
2026-07-05 21:59:50,805 [INFO] Agent 1250.0: F (+2), previous=2, shift=+0
2026-07-05 21:59:53,694 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 21:59:56,718 [INFO] Agent 1904.0: F (+2), previous=1, shift=+1
2026-07-05 21:59:59,456 [INFO] Agent 1900.0: E (+1), previous=1, shift=+0
2026-07-05 22:00:02,888 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 22:00:02,890 [INFO] Mean shift: +0.21
2026-07-05 22:00:02,892 [INFO] Shift distribution:
shift
-1     1
 0    18
 1     4
 2     1
2026-07-05 22:00:02,892 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(2), day 1
2026-07-05 22:00:05,947 [INFO] Agent 165.0: F (+2), previous=0, shift=+2
2026-07-05 22:00:09,283 [INFO] Agent 582.0: F (+2), previous=0, shift=+2
2026-07-05 22:00:12,628 [INFO] Agent 1379.0: C (-1), previous=0, shift=-1
2026-07-05 22:00:16,096 [INFO] Agent 713.0: A (-3), previous=-3, shift=+0
2026-07-05 22:00:20,459 [INFO] Agent 1878.0: B (-2), previous=-1, shift=-1
2026-07-05 22:00:23,443 [INFO] Agent 844.0: F (+2), previous=2, shift=+0
2026-07-05 22:00:26,723 [INFO] Agent 409.0: F (+2), previous=2, shift=+0
2026-07-05 22:00:29,491 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 22:00:32,484 [INFO] Agent 91.0: E (+1), previous=1, shift=+0
2026-07-05 22:00:36,024 [INFO] Agent 69.0: F (+2), previous=0, shift=+2
2026-07-05 22:00:39,401 [INFO] Agent 166.0: G (+3), previous=3, shift=+0
2026-07-05 22:00:42,844 [INFO] Agent 103.0: B (-2), previous=-2, shift=+0
2026-07-05 22:00:46,289 [INFO] Agent 1262.0: F (+2), previous=0, shift=+2
2026-07-05 22:00:49,593 [INFO] Agent 377.0: E (+1), previous=2, shift=-1
2026-07-05 22:00:52,931 [INFO] Agent 574.0: B (-2), previous=0, shift=-2
2026-07-05 22:00:56,468 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 22:01:01,622 [INFO] Agent 752.0: B (-2), previous=-2, shift=+0
2026-07-05 22:01:04,738 [INFO] Agent 1001.0: F (+2), previous=2, shift=+0
2026-07-05 22:01:07,674 [INFO] Agent 440.0: G (+3), previous=3, shift=+0
2026-07-05 22:01:11,279 [INFO] Agent 1250.0: F (+2), previous=0, shift=+2
2026-07-05 22:01:14,972 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 22:01:18,097 [INFO] Agent 1904.0: C (-1), previous=-1, shift=+0
2026-07-05 22:01:21,345 [INFO] Agent 1900.0: E (+1), previous=0, shift=+1
2026-07-05 22:01:25,302 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 22:01:25,303 [INFO] Mean shift: +0.25
2026-07-05 22:01:25,305 [INFO] Shift distribution:
shift
-2     1
-1     3
 0    14
 1     1
 2     5
2026-07-05 22:01:25,306 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(6), day 1
2026-07-05 22:01:28,600 [INFO] Agent 165.0: E (+1), previous=1, shift=+0
2026-07-05 22:01:31,629 [INFO] Agent 582.0: B (-2), previous=-1, shift=-1
2026-07-05 22:01:50,231 [INFO] Agent 1379.0: E (+1), previous=1, shift=+0
2026-07-05 22:01:53,119 [INFO] Agent 713.0: A (-3), previous=-3, shift=+0
2026-07-05 22:01:56,234 [INFO] Agent 1878.0: F (+2), previous=0, shift=+2
2026-07-05 22:01:59,385 [INFO] Agent 844.0: B (-2), previous=-2, shift=+0
2026-07-05 22:02:02,246 [INFO] Agent 409.0: F (+2), previous=2, shift=+0
2026-07-05 22:02:05,807 [INFO] Agent 1957.0: E (+1), previous=1, shift=+0
2026-07-05 22:02:08,840 [INFO] Agent 91.0: D (+0), previous=0, shift=+0
2026-07-05 22:02:11,778 [INFO] Agent 69.0: F (+2), previous=-2, shift=+4
2026-07-05 22:02:14,717 [INFO] Agent 166.0: E (+1), previous=1, shift=+0
2026-07-05 22:02:17,969 [INFO] Agent 103.0: B (-2), previous=-3, shift=+1
2026-07-05 22:02:21,009 [INFO] Agent 1262.0: B (-2), previous=-2, shift=+0
2026-07-05 22:02:24,686 [INFO] Agent 377.0: F (+2), previous=0, shift=+2
2026-07-05 22:02:27,730 [INFO] Agent 574.0: F (+2), previous=0, shift=+2
2026-07-05 22:02:31,061 [INFO] Agent 556.0: E (+1), previous=1, shift=+0
2026-07-05 22:02:33,638 [INFO] Agent 752.0: B (-2), previous=-2, shift=+0
2026-07-05 22:02:37,154 [INFO] Agent 1001.0: C (-1), previous=-1, shift=+0
2026-07-05 22:02:40,435 [INFO] Agent 440.0: E (+1), previous=1, shift=+0
2026-07-05 22:02:43,680 [INFO] Agent 1250.0: F (+2), previous=1, shift=+1
2026-07-05 22:02:46,812 [INFO] Agent 355.0: F (+2), previous=2, shift=+0
2026-07-05 22:02:50,144 [INFO] Agent 1904.0: B (-2), previous=-3, shift=+1
2026-07-05 22:02:52,790 [INFO] Agent 1900.0: E (+1), previous=2, shift=-1
2026-07-05 22:02:56,180 [INFO] Agent 620.0: D (+0), previous=0, shift=+0
2026-07-05 22:02:56,181 [INFO] Mean shift: +0.46
2026-07-05 22:02:56,183 [INFO] Shift distribution:
shift
-1     2
 0    15
 1     3
 2     3
 4     1
2026-07-05 22:02:56,184 [INFO] Day 1 mean package index: +1.09
2026-07-05 22:02:56,185 [INFO] --- Day 2/3 (package=climate_policy_package, phases=['P-B', 'P-A', 'C']) ---
2026-07-05 22:04:41,042 [INFO] [P-B] Day 2: delivered package message to 15 citizens. Message (first 120 chars): A common-sense plan for cheap power has three steps: remove the carbon tax from generation, end the Renewable Obligation...
2026-07-05 22:04:41,043 [INFO] [P-B] Sample package reflection: Accelerate roll-out of renewable energy (e.g. more offshore and onshore wind parks): Somewhat support. I like the argument that more domestic renewables can act as insurance against future price shock...
2026-07-05 22:05:18,391 [INFO] [P-A] Day 2: delivered package message to 6 citizens. Message (first 120 chars): Communities should share directly in the benefits of nearby renewable projects through lower bills, community ownership ...
2026-07-05 22:05:18,392 [INFO] [P-A] Sample package reflection: - Accelerate the roll-out of renewable energy production (e.g. more offshore and onshore wind parks): Somewhat support. I like the “insurance against the next price shock” argument and the local air‑q...
2026-07-05 22:07:17,579 [INFO] [C] Day 2: 24 citizens generated package messages, 17 citizens reflected.
2026-07-05 22:07:17,580 [INFO] [C] Sample package message: I generally support a steady, well‑planned roll‑out of renewables (some concerns about costs, siting and community benefit), and I’m somewhat in favour of banning new oil/gas/coal licences if there ar...
2026-07-05 22:07:17,581 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(1), day 2
2026-07-05 22:07:20,812 [INFO] Agent 165.0: F (+2), previous=2, shift=+0
2026-07-05 22:07:23,908 [INFO] Agent 582.0: F (+2), previous=2, shift=+0
2026-07-05 22:07:26,775 [INFO] Agent 1379.0: E (+1), previous=2, shift=-1
2026-07-05 22:07:29,871 [INFO] Agent 713.0: E (+1), previous=1, shift=+0
2026-07-05 22:07:32,873 [INFO] Agent 1878.0: F (+2), previous=2, shift=+0
2026-07-05 22:07:35,808 [INFO] Agent 844.0: G (+3), previous=3, shift=+0
2026-07-05 22:07:38,529 [INFO] Agent 409.0: F (+2), previous=2, shift=+0
2026-07-05 22:07:41,424 [INFO] Agent 1957.0: G (+3), previous=3, shift=+0
2026-07-05 22:07:45,705 [INFO] Agent 91.0: F (+2), previous=2, shift=+0
2026-07-05 22:07:51,071 [INFO] Agent 69.0: F (+2), previous=2, shift=+0
2026-07-05 22:07:54,061 [INFO] Agent 166.0: G (+3), previous=3, shift=+0
2026-07-05 22:07:56,889 [INFO] Agent 103.0: G (+3), previous=3, shift=+0
2026-07-05 22:08:00,136 [INFO] Agent 1262.0: F (+2), previous=2, shift=+0
2026-07-05 22:08:03,282 [INFO] Agent 377.0: F (+2), previous=2, shift=+0
2026-07-05 22:08:06,559 [INFO] Agent 574.0: F (+2), previous=2, shift=+0
2026-07-05 22:08:11,806 [INFO] Agent 556.0: G (+3), previous=3, shift=+0
2026-07-05 22:08:14,983 [INFO] Agent 752.0: F (+2), previous=2, shift=+0
2026-07-05 22:08:18,626 [INFO] Agent 1001.0: E (+1), previous=1, shift=+0
2026-07-05 22:08:21,536 [INFO] Agent 440.0: G (+3), previous=3, shift=+0
2026-07-05 22:08:24,130 [INFO] Agent 1250.0: F (+2), previous=2, shift=+0
2026-07-05 22:08:27,532 [INFO] Agent 355.0: G (+3), previous=3, shift=+0
2026-07-05 22:08:30,317 [INFO] Agent 1904.0: F (+2), previous=2, shift=+0
2026-07-05 22:08:33,296 [INFO] Agent 1900.0: F (+2), previous=1, shift=+1
2026-07-05 22:08:36,248 [INFO] Agent 620.0: C (-1), previous=-1, shift=+0
2026-07-05 22:08:36,249 [INFO] Mean shift: +0.00
2026-07-05 22:08:36,251 [INFO] Shift distribution:
shift
-1     1
 0    22
 1     1
2026-07-05 22:08:36,251 [INFO] Running end-of-day survey for 24 agents, policy ClimatePolicyID(3), day 2
2026-07-05 22:08:39,333 [INFO] Agent 165.0: F (+2), previous=2, shift=+0
2026-07-05 22:08:42,583 [INFO] Agent 582.0: F (+2), previous=2, shift=+0
2026-07-05 22:08:45,710 [INFO] Agent 1379.0: C (-1), previous=-1, shift=+0
2026-07-05 22:08:48,742 [INFO] Agent 713.0: A (-3), previous=-3, shift=+0

Saved run to ../data/output/smoke/nb42_degree

### Verify Feature 2 - degree kept the hubs

`targeting_diagnostics.csv` only tracks `|GT|` (which does *not* discriminate centrality), so we
verify directly: reconstruct the peer graph from `network_snapshot.json`, then compare the mean
degree of the reached vs dropped members of side A's audience.

In [6]:
import networkx as nx

snap = json.loads((OUT_B / 'network_snapshot.json').read_text())
G = nx.Graph()
for node in snap['nodes']:
    G.add_node(node['id'])
for u, v in snap['edges']:
    G.add_edge(u, v)
deg = {str(k): v for k, v in dict(G.degree()).items()}

attrs_b = pd.read_csv(OUT_B / 'agent_attributes.csv')
aud = attrs_b[attrs_b['political_exposure'].isin(['A-only', 'both'])].copy()
aud['degree'] = aud['agent_id'].astype(str).map(deg)
reached = aud[aud['reached_by_a'] == True]
dropped = aud[aud['reached_by_a'] == False]
mk, md = reached['degree'].mean(), dropped['degree'].mean()
print(f'side A audience n={len(aud)}: reached mean degree={mk:.2f} vs dropped mean degree={md:.2f}')
assert mk > md, 'FAIL: degree targeting did not keep the higher-degree (hub) audience'
print('PASS: degree targeting kept the more-central audience.')

side A audience n=15: reached mean degree=9.17 vs dropped mean degree=3.67
PASS: degree targeting kept the more-central audience.

## 5. New-output sanity checks (byproduct of the runs)

`agent_prompts.csv` should hold the full prompt trail for the stratified sample (~1 agent per
bucket), across every persona-facing stage. `bucket_summary.csv` is the one-row-per-bucket
cross-run seed.

In [7]:
ap = pd.read_csv(OUT_A / 'agent_prompts.csv')
print('agent_prompts.csv rows:', len(ap))
print('sampled agents:', ap['agent_id'].nunique(), '->', sorted(ap['agent_id'].unique()))
print('stages captured:', sorted(ap['stage'].unique()))
expected = {'seed_rationale', 'survey_reasoning', 'survey_answer',
            'reflection_broadcast', 'reflection_peer', 'peer_message'}
missing = expected - set(ap['stage'].unique())
print('missing stages:', missing or 'none')

one = ap[ap['agent_id'] == ap['agent_id'].iloc[0]].sort_values('prompt_seq')
print(f"\nPrompt sequence for agent {one['agent_id'].iloc[0]}:")
display(one[['prompt_seq', 'day', 'phase', 'stage', 'policy_id']].head(30))

print('\nbucket_summary.csv:')
display(pd.read_csv(OUT_A / 'bucket_summary.csv'))

agent_prompts.csv rows: 200
sampled agents: 4 -> [np.float64(103.0), np.float64(355.0), np.float64(620.0), np.float64(1001.0)]
stages captured: ['peer_message', 'reflection_broadcast', 'reflection_peer', 'seed_rationale', 'survey_answer', 'survey_reasoning']
missing stages: none

Prompt sequence for agent 103.0:

    prompt_seq  day   phase             stage               policy_id
0            0    0     NaN    seed_rationale      ClimatePolicyID(1)
1            1    0     NaN    seed_rationale      ClimatePolicyID(2)
2            2    0     NaN    seed_rationale      ClimatePolicyID(3)
3            3    0     NaN    seed_rationale      ClimatePolicyID(4)
4            4    0     NaN    seed_rationale      ClimatePolicyID(5)
5            5    0     NaN    seed_rationale      ClimatePolicyID(6)
6            6    1       C      peer_message  climate_policy_package
7            7    1       C   reflection_peer  climate_policy_package
8            8    1  survey  survey_reasoning      ClimatePolicyID(3)
9            9    1  survey     survey_answer      ClimatePolicyID(3)
10          10    1  survey  survey_reasoning      ClimatePolicyID(5)
11          11    1  survey     survey_answer      ClimatePolicyID(5)
12          12    1  survey  survey_reasoning      ClimatePolicyID(4)
13          13    1  survey     survey_answer      ClimatePolicyID(4)
14          14    1  survey  survey_reasoning      ClimatePolicyID(1)
15          15    1  survey     survey_answer      ClimatePolicyID(1)
16          16    1  survey  survey_reasoning      ClimatePolicyID(2)
17          17    1  survey     survey_answer      ClimatePolicyID(2)
18          18    1  survey  survey_reasoning      ClimatePolicyID(6)
19          19    1  survey     survey_answer      ClimatePolicyID(6)
20          20    2       C      peer_message  climate_policy_package
21          21    2       C   reflection_peer  climate_policy_package
22          22    2  survey  survey_reasoning      ClimatePolicyID(1)
23          23    2  survey     survey_answer      ClimatePolicyID(1)
24          24    2  survey  survey_reasoning      ClimatePolicyID(3)
25          25    2  survey     survey_answer      ClimatePolicyID(3)
26          26    2  survey  survey_reasoning      ClimatePolicyID(4)
27          27    2  survey     survey_answer      ClimatePolicyID(4)
28          28    2  survey  survey_reasoning      ClimatePolicyID(5)
29          29    2  survey     survey_answer      ClimatePolicyID(5)

bucket_summary.csv:

,run_label,political_exposure,n_agents,day0_gt_mean,end_mean,drift,mae,rank_rho,reached_a,reached_b
0,NaN,A-only,1,2.666667,2.666667,-3.333338e-10,3.333338e-10,NaN,0,0
1,NaN,B-only,1,-0.666667,-0.333333,3.333333e-01,3.333333e-01,NaN,0,1
2,NaN,both,14,1.023810,1.273810,2.500000e-01,2.500000e-01,0.924375,6,14
3,NaN,neither,8,0.020833,0.708333,6.875000e-01,6.875000e-01,0.506211,0,0
4,NaN,TOTAL,24,0.687500,1.076389,3.888889e-01,3.888889e-01,0.950810,6,15

## 6. Summary

If all three asserts passed (persuadable `|GT|`, degree hubs, stages captured), the two features and
the new output artefacts are wired correctly end-to-end. **NB 43** loads `nb42_persuadable` for the
full prompt walkthrough and the O2 figure gallery.